### ISSUE TITLE
Gnome control center segfault

### ISSUE THREAD

**Issue by montagdude** [Dlackware/gnome-systemd#19]
I'm getting this error when I try to click the "Details" entry in Gnome control center:

```
$ gnome-control-center --overview
(gnome-control-center:31934): GLib-CRITICAL **: g_regex_replace: assertion 'string != NULL' failed
Segmentation fault (core dumped)
```
This is on the 3.22/14.2 branch built on Slackware64 14.2.

**Comment by belka-ew** [comment]
Updated some packages yesterday but the bug is still there (and it came in with some update). Thanks for reporting!

gnome-control-center stack trace for me for future reference:
```
Thread 1 "gnome-control-c" received signal SIGSEGV, Segmentation fault.
0x000000000048da48 in remove_duplicate_whitespace ()
(gdb) where
#0  0x000000000048da48 in remove_duplicate_whitespace ()
#1  0x000000000048dab4 in info_cleanup ()
#2  0x000000000048a175 in get_renderer_from_session ()
#3  0x000000000048a4f5 in get_graphics_data ()
#4  0x000000000048d54e in cc_info_panel_init ()
#5  0x00007fffdd6e4179 in g_type_create_instance () at /usr/lib64/../lib64/libgobject-2.0.so.0
#6  0x00007fffdd6c69bb in  () at /usr/lib64/../lib64/libgobject-2.0.so.0
#7  0x00007fffdd6c8735 in g_object_new_valist () at /usr/lib64/../lib64/libgobject-2.0.so.0
#8  0x00007fffdd6c8a84 in g_object_new () at /usr/lib64/../lib64/libgobject-2.0.so.0
#9  0x000000000045411f in cc_panel_loader_load_by_name ()
#10 0x000000000045664e in activate_panel ()
#11 0x0000000000458b1f in cc_window_set_active_panel_from_id ()
#12 0x0000000000456d5a in item_activated_cb ()
#13 0x00007fffdd4afd2c in ffi_call_unix64 () at /usr/lib64/../lib64/libffi.so.6
#14 0x00007fffdd4af835 in ffi_call () at /usr/lib64/../lib64/libffi.so.6
#15 0x00007fffdd6c21b3 in g_cclosure_marshal_generic () at /usr/lib64/../lib64/libgobject-2.0.so.0
#16 0x00007fffdd6c19b5 in g_closure_invoke () at /usr/lib64/../lib64/libgobject-2.0.so.0
#17 0x00007fffdd6d31c1 in  () at /usr/lib64/../lib64/libgobject-2.0.so.0
#18 0x00007fffdd6dbdef in g_signal_emit_valist () at /usr/lib64/../lib64/libgobject-2.0.so.0
#19 0x00007fffdd6dc112 in g_signal_emit () at /usr/lib64/../lib64/libgobject-2.0.so.0
#20 0x0000000000452424 in iconview_item_activated_cb ()
#21 0x00007fffdd6c19b5 in g_closure_invoke () at /usr/lib64/../lib64/libgobject-2.0.so.0
#22 0x00007fffdd6d31c1 in  () at /usr/lib64/../lib64/libgobject-2.0.so.0
#23 0x00007fffdd6dbdef in g_signal_emit_valist () at /usr/lib64/../lib64/libgobject-2.0.so.0
#24 0x00007fffdd6dc112 in g_signal_emit () at /usr/lib64/../lib64/libgobject-2.0.so.0
#25 0x00007fffe4f710cc in  () at /usr/lib64/../lib64/libgtk-3.so.0
#26 0x00007fffe4f9a637 in  () at /usr/lib64/../lib64/libgtk-3.so.0
#27 0x00007fffdd6c1be4 in  () at /usr/lib64/../lib64/libgobject-2.0.so.0
#28 0x00007fffdd6db55b in g_signal_emit_valist () at /usr/lib64/../lib64/libgobject-2.0.so.0
#29 0x00007fffdd6dc112 in g_signal_emit () at /usr/lib64/../lib64/libgobject-2.0.so.0
#30 0x00007fffe50dfb14 in  () at /usr/lib64/../lib64/libgtk-3.so.0
#31 0x00007fffe4f9768e in  () at /usr/lib64/../lib64/libgtk-3.so.0
#32 0x00007fffe4f99682 in gtk_main_do_event () at /usr/lib64/../lib64/libgtk-3.so.0
#33 0x00007fffe4aba5b5 in  () at /usr/lib64/../lib64/libgdk-3.so.0
#34 0x00007fffe4b0da22 in  () at /usr/lib64/../lib64/libgdk-3.so.0
#35 0x00007fffdd1e0f57 in g_main_context_dispatch () at /usr/lib64/../lib64/libglib-2.0.so.0
#36 0x00007fffdd1e1188 in  () at /usr/lib64/../lib64/libglib-2.0.so.0
#37 0x00007fffdd1e122c in g_main_context_iteration () at /usr/lib64/../lib64/libglib-2.0.so.0
#38 0x00007fffdea6bebd in g_application_run () at /usr/lib64/../lib64/libgio-2.0.so.0
#39 0x0000000000450ba8 in main ()
```

**Comment by belka-ew** [comment]
Fixed in 3.22.2, build 2.

The code in the gnome-control-center master is unchanged. I probably should report the issue to upstream and merge the patch into our master. I leave the issue open till then.

**Comment by montagdude** [comment]
I rebuilt and the segfault is gone here. Thanks for the fix.
